package com.smartdoc.ai.provider;
import com.baomidou.mybatisplus.core.toolkit.Wrappers; import org.springframework.dao.DuplicateKeyException; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
public class AiProviderService { private final AiProviderMapper providers;private final AiRoutingMapper routes;private final ProviderSecretVault vault;private final ProviderUrlPolicy urls;private final ModelRouter router; private final com.smartdoc.ai.DailyAiQuota quota;
 public AiProviderService(AiProviderMapper p,AiRoutingMapper r,ProviderSecretVault v,ProviderUrlPolicy u,ModelRouter m,com.smartdoc.ai.DailyAiQuota q){providers=p;routes=r;vault=v;urls=u;router=m;quota=q;}
 public List<ProviderView> list(long user){List<ProviderView> out=new ArrayList<>();for(AiProviderConfig p:providers.listOwned(user))out.add(view(user,p));return out;} public ProviderView get(long user,long id){AiProviderConfig p=owned(user,id);return view(user,p);}
 @Transactional public ProviderView create(long user,ProviderCreateRequest r){AiProviderConfig p=from(r);p.setUserId(user);p.setCreatedAt(LocalDateTime.now());p.setUpdatedAt(p.getCreatedAt());try{if(providers.insert(p)!=1)throw new IllegalStateException("Provider creation failed");try{if(nonBlank(r.getApiKey()))vault.save(user,p.getId(),r.getApiKey(),p);return view(user,providers.selectOwned(p.getId(),user));}catch(RuntimeException e){providers.deleteOwned(p.getId(),user);throw e;}}catch(DuplicateKeyException e){throw new IllegalArgumentException("Provider display name already exists");}}
 @Transactional public ProviderView update(long user,long id,ProviderUpdateRequest r){AiProviderConfig old=owned(user,id),next=from(r);next.setId(id);next.setUserId(user);next.setCreatedAt(old.getCreatedAt());next.setUpdatedAt(LocalDateTime.now());if(providers.updateOwned(next,user)!=1)throw new NoSuchElementException();if(nonBlank(r.getApiKey()))vault.save(user,id,r.getApiKey(),next);return view(user,providers.selectOwned(id,user));}
 @Transactional public void clearKey(long user,long id){owned(user,id);vault.clear(user,id);}
 @Transactional public void delete(long user,long id){owned(user,id);AiRoutingConfig r=routes.selectOwned(user);if(r!=null&&(Objects.equals(r.getDefaultTextProviderId(),id)||Objects.equals(r.getDefaultVisionProviderId(),id)))throw new IllegalStateException("Provider is referenced by routing");vault.clear(user,id);if(providers.deleteOwned(id,user)!=1)throw new NoSuchElementException();}
 public AiRoutingConfig routing(long user){AiRoutingConfig r=routes.selectOwned(user);if(r==null){r=new AiRoutingConfig();r.setUserId(user);r.setDailyLimit(50);r.setMaxOutputTokens(1024);r.setUpdatedAt(LocalDateTime.now());}return r;}
 @Transactional public AiRoutingConfig updateRouting(long user,RoutingUpdateRequest request){if(request==null||request.getDailyLimit()<1||request.getDailyLimit()>500||request.getMaxOutputTokens()<128||request.getMaxOutputTokens()>4096)throw new IllegalArgumentException("Invalid routing limits");checkReference(user,request.getDefaultTextProviderId(),ProviderCapability.TEXT);checkReference(user,request.getDefaultVisionProviderId(),ProviderCapability.VISION);AiRoutingConfig r=new AiRoutingConfig();r.setUserId(user);r.setDefaultTextProviderId(request.getDefaultTextProviderId());r.setDefaultVisionProviderId(request.getDefaultVisionProviderId());r.setDailyLimit(request.getDailyLimit());r.setMaxOutputTokens(request.getMaxOutputTokens());r.setUpdatedAt(LocalDateTime.now());if(routes.updateOwned(r)==0)routes.insert(r);return r;}
 public Map<String,Object> test(long user,long id){AiProviderConfig p=owned(user,id);if(!Boolean.TRUE.equals(p.getEnabled()))throw new ProviderHttpException("MODEL_NOT_CONFIGURED",400);if(!p.supports(ProviderCapability.TEXT))throw new ProviderHttpException("UNSUPPORTED_CAPABILITY",400);String key=vault.load(user,id,p).orElseThrow(ProviderKeyMissingException::new);long start=System.nanoTime();quota.consume(user,routing(user).getDailyLimit());router.adapterFor(p).probe(p,key);return Map.of("success",true,"providerId",id,"model",p.getModel(),"latencyMs",(System.nanoTime()-start)/1_000_000);}
 private void checkReference(long user,Long id,ProviderCapability capability){if(id==null)return;AiProviderConfig p=providers.selectOwnedEnabled(id,user);if(p==null||!p.supports(capability))throw new IllegalArgumentException("Routing provider is not available");}
 private ProviderView view(long u,AiProviderConfig p){return ProviderView.of(p,vault.keyConfigured(u,p.getId(),p),vault.persistenceAvailable());} private AiProviderConfig owned(long u,long id){AiProviderConfig p=providers.selectOwned(id,u);if(p==null)throw new NoSuchElementException();return p;}
 private AiProviderConfig from(ProviderCreateRequest r){if(r==null||!nonBlank(r.getDisplayName())||r.getDisplayName().codePointCount(0,r.getDisplayName().length())>80||!nonBlank(r.getModel())||r.getModel().codePointCount(0,r.getModel().length())>120||!r.isSupportsText()&&!r.isSupportsVision())throw new IllegalArgumentException("Invalid provider settings");AiProviderConfig p=new AiProviderConfig();p.setDisplayName(r.getDisplayName().trim());p.setPresetCode(requirePreset(r.getPresetCode()));p.setProtocol(requireProtocol(r.getProtocol()));p.setBaseUrl(urls.validateAndNormalize(r.getBaseUrl()));p.setModel(r.getModel().trim());p.setSupportsText(r.isSupportsText());p.setSupportsVision(r.isSupportsVision());p.setEnabled(r.isEnabled());return p;} private static boolean nonBlank(String s){return s!=null&&!s.trim().isEmpty();} private static String requirePreset(String s){try{return AiProviderPreset.valueOf(s).name();}catch(Exception e){throw new IllegalArgumentException("Unsupported provider preset");}} private static String requireProtocol(String s){try{return AiProviderProtocol.valueOf(s).name();}catch(Exception e){throw new IllegalArgumentException("Unsupported provider protocol");}}
}
