package com.smartdoc.ai.provider;
import com.fasterxml.jackson.databind.*; import org.springframework.http.*; import org.springframework.http.client.ClientHttpResponse; import org.springframework.web.client.*; import java.net.*; import java.io.*; import java.util.*;
public class OpenAiChatCompletionsAdapter implements ProviderAdapter { private final RestTemplate http; private final ObjectMapper json; private final int cap; private final ProviderUrlPolicy urls;
 public OpenAiChatCompletionsAdapter(RestTemplate h,ObjectMapper j,int c){this(h,j,c,new ProviderUrlPolicy(false,false));} public OpenAiChatCompletionsAdapter(RestTemplate h,ObjectMapper j,int c,ProviderUrlPolicy u){http=h;json=j;cap=c;urls=u;http.setErrorHandler(new ResponseErrorHandler(){public boolean hasError(ClientHttpResponse response){return false;}public void handleError(ClientHttpResponse response){}});}
 public AiProviderProtocol protocol(){return AiProviderProtocol.OPENAI_CHAT_COMPLETIONS;}
 public ProviderResponse complete(AiProviderConfig config,String key,TextCompletionRequest request){try{URI endpoint=URI.create(config.getBaseUrl().replaceAll("/+$","")+"/").resolve("chat/completions");urls.assertSafeResolved(endpoint);HttpHeaders headers=new HttpHeaders();headers.setContentType(MediaType.APPLICATION_JSON);headers.setBearerAuth(key);Map<String,Object> body=new LinkedHashMap<>();body.put("model",config.getModel());body.put("temperature",0.2);body.put("max_tokens",request.getMaxOutputTokens());List<Map<String,String>> messages=new ArrayList<>();if(!request.getSystem().isBlank())messages.add(Map.of("role","system","content",request.getSystem()));messages.add(Map.of("role","user","content",request.getPrompt()));body.put("messages",messages);byte[] requestBytes=json.writeValueAsBytes(body);byte[] bytes=http.execute(endpoint,HttpMethod.POST,clientRequest->{clientRequest.getHeaders().putAll(headers);clientRequest.getBody().write(requestBytes);},response->readAndMap(response));JsonNode root=json.readTree(bytes);String answer=root.path("choices").path(0).path("message").path("content").asText();if(answer==null||answer.trim().isEmpty())throw new ProviderHttpException("INVALID_PROVIDER_RESPONSE",502);return new ProviderResponse(answer);}catch(ProviderHttpException e){throw e;}catch(ResourceAccessException e){throw new ProviderHttpException("PROVIDER_TIMEOUT",504);}catch(Exception e){throw new ProviderHttpException("INVALID_PROVIDER_RESPONSE",502);}}
 private byte[] readAndMap(ClientHttpResponse response)throws IOException{byte[] bytes=readCapped(response);int status=response.getRawStatusCode();if(status>=400)throw statusError(status);return bytes;}
 private ProviderHttpException statusError(int status){String code=status==401||status==403?"PROVIDER_AUTH_FAILED":status==404?"MODEL_NOT_FOUND":status==429?"PROVIDER_RATE_LIMITED":status>=500?"PROVIDER_UNAVAILABLE":"PROVIDER_REQUEST_FAILED";return new ProviderHttpException(code,502);}
 private byte[] readCapped(ClientHttpResponse response)throws IOException{long declared=response.getHeaders().getContentLength();if(declared>cap)throw new ProviderHttpException("RESPONSE_TOO_LARGE",502);try(InputStream in=response.getBody();ByteArrayOutputStream out=new ByteArrayOutputStream((int)Math.min(Math.max(0,declared),cap))){byte[] buffer=new byte[8192];int n,total=0;while((n=in.read(buffer))!=-1){if(total+n>cap)throw new ProviderHttpException("RESPONSE_TOO_LARGE",502);out.write(buffer,0,n);total+=n;}return out.toByteArray();}}
 public ProviderResponse probe(AiProviderConfig c,String k){return complete(c,k,new TextCompletionRequest("","Reply with OK only.",1));} public ProviderResponse vision(AiProviderConfig c,String k,VisionCompletionRequest r){throw new ProviderHttpException("UNSUPPORTED_CAPABILITY",400);}
}
