<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useDocumentsStore } from '../stores/documents'
import { recentNotes, recentReading, type NoteView, type RecentDocument } from '../api/search'
import GlobalSearch from '../components/GlobalSearch.vue'
import AppIcon from '../components/AppIcon.vue'
const store = useDocumentsStore(); const notes = ref<NoteView[]>([]); const recent = ref<RecentDocument[]>([]); const loading = ref(true); const error = ref('')
const favorites = computed(() => store.documents.filter((document) => document.favorite).length)
const load = async () => { loading.value = true; error.value = ''; const started = Date.now(); try { await store.loadDocuments(); if (store.error) throw new Error(store.error); [recent.value, notes.value] = await Promise.all([recentReading(), recentNotes()]) } catch { error.value = '工作台数据暂时无法加载' } finally { window.setTimeout(() => { loading.value = false }, Math.max(0, 300 - (Date.now() - started))) } }
const chooseFiles = (event: Event) => { const files = Array.from((event.target as HTMLInputElement).files ?? []); if (files.length) void store.uploadFiles(files) }
onMounted(load)
</script>
<template><div class="page dashboard-page"><header class="dashboard-hero"><div><p class="eyebrow">WORKSPACE</p><h1>继续你的学习进度</h1><p>资料、笔记和阅读位置都在这里，随时接着上次的位置。</p></div><label class="button primary"><AppIcon name="upload"/>快速上传<input type="file" multiple @change="chooseFiles"/></label></header><GlobalSearch/><div v-if="loading" class="dashboard-skeleton" aria-label="正在加载工作台"><span v-for="n in 6" :key="n"/></div><section v-else-if="error" class="feedback-state error-state"><h2>{{ error }}</h2><button class="button secondary" @click="load">重试</button></section><template v-else><section class="metrics-grid"><article><span>资料</span><strong>{{ store.documents.length }}</strong><small>已整理的学习资料</small></article><article><span>收藏</span><strong>{{ favorites }}</strong><small>重点资料</small></article><article><span>笔记</span><strong>{{ notes.length }}</strong><small>最近可回顾的记录</small></article><article class="phase-card"><span>复习</span><strong>第二阶段开放</strong><small>不会展示虚构的复习数据</small></article></section><section class="dashboard-grid"><article class="panel"><header><h2>最近阅读</h2><RouterLink to="/recent">查看全部</RouterLink></header><div v-if="recent.length" class="compact-list"><a v-for="item in recent.slice(0,5)" :key="item.id" :href="`/reader/${item.id}`"><span class="file-type">{{ item.documentType.slice(0,3) }}</span><span><strong>{{ item.name }}</strong><small>{{ item.pageCount ? `${item.pageCount} 页 · ` : '' }}继续阅读</small></span></a></div><div v-else class="compact-empty">打开一份资料后，阅读记录会显示在这里。</div></article><article class="panel"><header><h2>最近笔记</h2><RouterLink to="/notes">查看全部</RouterLink></header><div v-if="notes.length" class="compact-list"><a v-for="item in notes.slice(0,5)" :key="item.id" :href="`/reader/${item.documentId}${item.pageNumber ? `?page=${item.pageNumber}` : ''}`"><AppIcon name="note"/><span><strong>{{ item.contentMarkdown.slice(0,44) }}</strong><small>{{ item.pageNumber ? `来源：第 ${item.pageNumber} 页` : '独立笔记' }}</small></span></a></div><div v-else class="compact-empty">阅读时保存的笔记会集中出现在这里。</div></article></section></template></div></template>
