<script setup lang="ts">
import {computed,nextTick,onBeforeUnmount,onMounted,ref,watch} from 'vue'
import {onBeforeRouteLeave,useRoute} from 'vue-router'
import ReaderPdf from '../components/reader/ReaderPdf.vue'
import {copyCode,renderDocument} from '../reader/render'
import {getProgress,getReaderContent,getReaderDocument,listDocumentNotes,saveProgress,searchDocument,type Note} from '../api/reader'
import {createNote,deleteNote,runAi,updateNote,type AiAction,type AiResult} from '../api/study'

const route=useRoute(),id=Number(route.params.id),viewer=ref<HTMLElement>(),workspace=ref<HTMLElement>()
const loading=ref(true),error=ref(''),title=ref(''),type=ref('TXT'),language=ref('text'),content=ref(''),blob=ref<Blob>(),html=ref('')
const page=ref(Math.max(1,Number(route.query.page)||1)),pages=ref(1),zoom=ref(100),ratio=ref(0),restoring=ref(true),pageText=ref('')
const notes=ref<Note[]>([]),notesOpen=ref(false),aiOpen=ref(false),selection=ref(''),status=ref('')
const noteId=ref<number>(),noteBody=ref(''),noteFavorite=ref(false),noteTags=ref(''),noteSource=ref('')
const aiAction=ref<AiAction>('ASK'),question=ref(''),aiBusy=ref(false),aiResult=ref<AiResult>(),searchQuery=ref(''),searchHits=ref<{pageNumber:number;snippet:string}[]>([])
let progressTimer:number|undefined
const zoomRatio=computed(()=>Math.min(3,Math.max(.5,zoom.value/100))),notePreview=computed(()=>renderDocument('markdown',noteBody.value))
const contentKind=computed(()=>type.value==='PDF'?'pdf':language.value==='markdown'?'markdown':language.value==='text'?'text':'code')
const progressPayload=()=>({pageNumber:type.value==='PDF'?page.value:1,scrollRatio:ratio.value,zoom:zoomRatio.value})
const persist=()=>{window.clearTimeout(progressTimer);return saveProgress(id,progressPayload()).catch(()=>{status.value='阅读进度暂未保存'})}
const scheduleProgress=()=>{if(!viewer.value||restoring.value)return;const max=viewer.value.scrollHeight-viewer.value.clientHeight;ratio.value=max>0?viewer.value.scrollTop/max:0;window.clearTimeout(progressTimer);progressTimer=window.setTimeout(()=>void persist(),800)}
const changePage=(next:number)=>{page.value=Math.min(pages.value,Math.max(1,next));ratio.value=0;void persist()}
const restoreScroll=async()=>{await nextTick();if(viewer.value){viewer.value.scrollTop=(viewer.value.scrollHeight-viewer.value.clientHeight)*ratio.value}restoring.value=false}
const captureSelection=()=>{const value=window.getSelection()?.toString().trim()??'';if(value)selection.value=value.slice(0,8000)}
const editNote=(note?:Note)=>{noteId.value=note?.id;noteBody.value=note?.contentMarkdown??'';noteFavorite.value=note?.favorite??false;noteTags.value=note?.tags?.map(tag=>tag.id).join(', ')??'';noteSource.value=note?.sourceText??selection.value;notesOpen.value=true}
const notePayload=()=>({pageNumber:type.value==='PDF'?page.value:null,sourceText:noteSource.value||null,contentMarkdown:noteBody.value,favorite:noteFavorite.value,tagIds:noteTags.value.split(',').map(Number).filter(Number.isFinite)})
const saveNote=async()=>{if(!noteBody.value.trim()){status.value='请输入笔记正文';return}if(noteId.value){const updated=await updateNote(noteId.value,notePayload());notes.value=notes.value.map(note=>note.id===updated.id?updated:note)}else notes.value.unshift(await createNote(id,notePayload()));status.value='笔记已保存';editNote()}
const removeNote=async(note:Note)=>{await deleteNote(note.id);notes.value=notes.value.filter(item=>item.id!==note.id);status.value='笔记已删除'}
const jumpNote=(note:Note)=>{if(note.pageNumber)changePage(note.pageNumber);notesOpen.value=false}
const askAi=async(force=false)=>{if(aiBusy.value)return;aiBusy.value=true;try{aiResult.value=await runAi(id,{action:aiAction.value,question:question.value||undefined,selectedText:selection.value||undefined,pageNumber:type.value==='PDF'?page.value:undefined,force});status.value=aiResult.value.cached?'已返回缓存结果':'AI 结果已生成'}catch{status.value='AI 操作失败，请检查设置或稍后重试'}finally{aiBusy.value=false}}
const runSearch=async()=>{if(searchQuery.value.trim().length<2){searchHits.value=[];return}searchHits.value=await searchDocument(id,searchQuery.value.trim())}
const copy=async()=>{await copyCode(content.value);status.value='代码已复制'}
const copySelection=async()=>{await copyCode(selection.value);status.value='选区已复制'}
const fullscreen=async()=>{if(!document.fullscreenElement)await workspace.value?.requestFullscreen();else await document.exitFullscreen()}
const fit=()=>{zoom.value=100;void persist()}
onMounted(async()=>{try{const [document,progress,loadedNotes]=await Promise.all([getReaderDocument(id),getProgress(id),listDocumentNotes(id)]);title.value=document.name;type.value=document.documentType??'TXT';pages.value=document.pageCount??1;page.value=Math.min(pages.value,Math.max(1,Number(route.query.page)||progress.pageNumber));zoom.value=Math.round(progress.zoom*100);ratio.value=progress.scrollRatio;notes.value=loadedNotes;const body=await getReaderContent(id,type.value);if(body instanceof Blob)blob.value=body;else{language.value=body.language;content.value=body.content;if(body.language!=='text')html.value=renderDocument(body.language,body.content)}await restoreScroll()}catch{error.value='资料暂时无法加载'}finally{loading.value=false}})
watch(zoom,()=>{if(!restoring.value){window.clearTimeout(progressTimer);progressTimer=window.setTimeout(()=>void persist(),800)}})
const flush=()=>{window.clearTimeout(progressTimer);if(!loading.value)void persist()};onBeforeRouteLeave(flush);onBeforeUnmount(flush)
</script>

<template><div ref="workspace" class="reader-workspace"><header class="reader-toolbar"><RouterLink to="/library">返回资料库</RouterLink><strong>{{title||'阅读器'}}</strong><div class="reader-controls"><button aria-label="上一页" :disabled="page<=1" @click="changePage(page-1)">上一页</button><label v-if="contentKind==='pdf'">页码<input v-model.number="page" aria-label="页码" type="number" min="1" :max="pages" @change="changePage(page)"> / {{pages}}</label><button aria-label="下一页" :disabled="page>=pages" @click="changePage(page+1)">下一页</button><label>缩放<input v-model.number="zoom" aria-label="缩放比例" type="number" min="50" max="300">%</label><button @click="fit">适合页面</button><button @click="fullscreen">全屏</button></div><div><button data-test="mobile-notes-button" @click="notesOpen=!notesOpen">笔记</button><button @click="aiOpen=!aiOpen">AI</button></div></header>
<div class="reader-search"><label>资料内搜索<input v-model="searchQuery" placeholder="至少 2 个字符" @keyup.enter="runSearch"></label><button @click="runSearch">搜索</button><button v-for="hit in searchHits.slice(0,5)" :key="`${hit.pageNumber}-${hit.snippet}`" @click="changePage(hit.pageNumber)">第 {{hit.pageNumber}} 页：{{hit.snippet.slice(0,42)}}</button></div>
<div class="reader-layout"><main ref="viewer" data-test="reader-scroll" :data-restored-ratio="ratio" class="reader-document" @scroll="scheduleProgress" @mouseup="captureSelection"><p v-if="loading">正在加载…</p><p v-else-if="error" role="alert">{{error}}</p><ReaderPdf v-else-if="blob" :blob="blob" :page="page" :zoom="zoomRatio" @pages="pages=$event" @page="changePage" @text="pageText=$event"/><article v-else-if="contentKind==='markdown'" class="rendered-document" v-html="html"/><section v-else-if="contentKind==='code'" class="code-document"><button class="button secondary" @click="copy">复制代码</button><div class="rendered-document" v-html="html"/></section><pre v-else>{{content}}</pre></main>
<aside class="reader-side reader-notes" :class="{open:notesOpen}"><button class="drawer-close-reader" @click="notesOpen=false">关闭</button><h2>笔记</h2><div class="note-editor"><label>原文<textarea v-model="noteSource" rows="3"/></label><label>Markdown 笔记<textarea v-model="noteBody" rows="7"/></label><label>标签编号（逗号分隔）<input v-model="noteTags"></label><label><input v-model="noteFavorite" type="checkbox">收藏</label><div class="note-preview" v-html="notePreview"/><button class="button primary" @click="saveNote">{{noteId?'更新':'保存'}}笔记</button></div><article v-for="note in notes" :key="note.id" class="reader-note"><button @click="jumpNote(note)">{{note.pageNumber?`第 ${note.pageNumber} 页`:'正文'}}</button><p>{{note.contentMarkdown}}</p><button @click="editNote(note)">编辑</button><button @click="removeNote(note)">删除</button></article></aside>
<aside class="reader-side reader-ai" :class="{open:aiOpen}"><button class="drawer-close-reader" @click="aiOpen=false">关闭</button><h2>当前资料 AI</h2><select v-model="aiAction"><option value="ASK">提问</option><option value="SUMMARIZE_DOCUMENT">总结全文</option><option value="SUMMARIZE_PAGE">总结当前页</option><option value="EXPLAIN_SELECTION">解释选区</option><option value="SUMMARIZE_SELECTION">总结选区</option><option value="EXPLAIN_CODE">解释代码</option></select><textarea v-model="question" rows="4" placeholder="你的问题"></textarea><p v-if="selection">选区：{{selection.slice(0,160)}}</p><button class="button primary" :disabled="aiBusy" @click="askAi(false)">{{aiBusy?'处理中…':'提交'}}</button><article v-if="aiResult" class="ai-answer"><header><span>{{aiResult.mode}}</span><span>{{aiResult.cached?'缓存':'新生成'}}</span><time>{{aiResult.createdAt}}</time></header><p>{{aiResult.content}}</p><button v-if="aiResult.source.pageNumber" @click="changePage(aiResult.source.pageNumber)">跳转来源：第 {{aiResult.source.pageNumber}} 页</button><blockquote>{{aiResult.source.text}}</blockquote><button :disabled="aiBusy" @click="askAi(true)">强制重新生成</button></article></aside></div>
<div v-if="selection" class="selection-bar" role="toolbar" aria-label="选区操作"><button @click="noteSource=selection;editNote()">摘录</button><button @click="noteSource=selection;editNote()">写笔记</button><button @click="aiAction='EXPLAIN_SELECTION';aiOpen=true">AI 解释</button><button @click="aiAction='SUMMARIZE_SELECTION';aiOpen=true">AI 总结</button><button @click="copySelection">复制</button><button @click="selection=''">关闭</button></div><p class="sr-only" aria-live="polite">{{status}}</p></div></template>
